export const lyrics = [
  { track: '4 Inches Away', lyrics: "Too long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nHunting season in the North woods \nThe jack lights stand the deer so still \nThe hunters take their aim and they shoot to kill \nThe headlights blind him as he hides his hands inside his sweatshirt sleeves \nHis ass got beat black back at school \nNow there's ass for sale on 14th Street \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nNobody knows the trouble he's seen \nThe femme fatale and the attitude queen \nThe coked-up go-go boys downtown that sleep around \nDon't want to come down \nPlatform shoes walking thin white lines \nShots of booze and neon signs \nA knife in the back and a mouth full of trash \nIt's a night in the life of the nightlife \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nThere is hope but it's not your hope \nThere are dreams but they're not your dreams \nThere is love but it's not for you \nGo find some other things to do \n\nHe's inching down the runway of the same old club, the same old spot \nHis muscles feel a little small \nHis stomach feels a little soft \nHe's searching left and right to find somebody with a gentle eye \nA song is forming in his head \nA melody to hide inside \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand" },
  { track: 'Happy Now', lyrics: "Give me your tired, give me your poor\nGive me a kiss and a set of keys to your front door\nYour hands work hard for justice\nI want them on me now\n\nTurn on the christmas lights, get out your pen\nShow me the way you get inspired again\nDon't ask if I'm ok 'cus\nI'll just lie anyway\n\nCan you pick me up some nectarines\nAnd a pack of smokes\nI think, I think that's all I need\nTonight I'll strip you bare\nYou say how far, I'll take you there\n\nYou lie beside me in the dead of night\nWe love the hot buzz of the city lights\nTo be both far and near\nTo be both there and here\n\nGive me your tired, give me your poor\nGive me a kiss and a set of keys to your front door\nYour hands work hard for justice\nI want them on me now\nI want them on me now\nI want them on me now" },
  { track: 'Math', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Slow News Day', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Worthy', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Where I End', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'This Love Song', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: '50 Yellow Tulips', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: '4 Weeks', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'I Dare You', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Piece Of Sky', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Boys (live 1999)', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." }
];