export const lyrics = [
  { track: 'First Avenue', lyrics: "Constellation on the wall\nWho is the farthest of them all?\nI’m just a legend of the fall\nI’m just a zero\nFlew too close to the sun\nBy blazing wings I am undone\nI may never get the chance to be a hero\n\nOn our way to play First Avenue\nWe were gonna take the night\nBut I had damage that I had to do\nI can never make it right\n\nScattered like the leaves\nThe ones that die, the ones we grieve\nThe ones you love, the ones that leave\nAnd I should know\nShattered into shards\nDown on the tracks spray-painted cars\nAt 21 the world was ours\nIt’s time to go\n\nOn our way to play First Avenue\nWe were gonna take the night\nBut I had damage that I had to do\nI can never make it right\n\nThe harmonies were tight and so were we\nWe had some fight in us back then\nI never meant to hurt a friend\n\nOn our way to play First Avenue\nWe were gonna take the night\nBut I had damage that I had to do\nI can never make it right" },
  { track: 'Lake Street', lyrics: "I live my life along Lake Street\nToeing the 21 line\nI live my life along Lake Street\nI love this city sometimes\n\nAsphalt and pavement\nFor lease or for rent\nVintage and vinyl\nAll sales are final\nSupermercado\nFood stamps and lotto\nCowboys and Indians\nCondos and indie bands\n\nI live my life along Lake Street\nToeing the 21 line\nI live my life along Lake Street\nI love this city sometimes\n\nChain link and traffic signs\nCandies and clementines\nShirts pressed and dry cleaned\nDealers and dope fiends\nStreet style and streetwalkers\nHustlers and fast-talkers\nDrug stores and dance halls\nTobacco and catcalls\n\nI live my life along Lake Street\nToeing the 21 line\nI live my life along Lake Street\nI love this city sometimes\n\nBus stops and graveyards\nHippies and die-hards\nTattoos and Carharts\nCoffee and car parts\nCandles and rosaries\nDiesel and antifreeze\nHarleys and hipsters\nLittle trach twisters\n\nI live my life along Lake Street\nToeing the 21 line\nI live my life along Lake Street\nI love this city sometimes" },
  { track: 'Skyline', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Cold As Snow', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Good Times', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Spring Cocaine', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'The Weight of Not Forgetting You', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex consequat." },
  { track: 'Story of Us', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Skyline Heaven', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
];