export const lyrics = [
  { track: 'Razor In His Hand', lyrics: "Too long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nHunting season in the North woods \nThe jack lights stand the deer so still \nThe hunters take their aim and they shoot to kill \nThe headlights blind him as he hides his hands inside his sweatshirt sleeves \nHis ass got beat black back at school \nNow there's ass for sale on 14th Street \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nNobody knows the trouble he's seen \nThe femme fatale and the attitude queen \nThe coked-up go-go boys downtown that sleep around \nDon't want to come down \nPlatform shoes walking thin white lines \nShots of booze and neon signs \nA knife in the back and a mouth full of trash \nIt's a night in the life of the nightlife \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nThere is hope but it's not your hope \nThere are dreams but they're not your dreams \nThere is love but it's not for you \nGo find some other things to do \n\nHe's inching down the runway of the same old club, the same old spot \nHis muscles feel a little small \nHis stomach feels a little soft \nHe's searching left and right to find somebody with a gentle eye \nA song is forming in his head \nA melody to hide inside \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand" },
  { track: 'On Me Now', lyrics: "Give me your tired, give me your poor\nGive me a kiss and a set of keys to your front door\nYour hands work hard for justice\nI want them on me now\n\nTurn on the christmas lights, get out your pen\nShow me the way you get inspired again\nDon't ask if I'm ok 'cus\nI'll just lie anyway\n\nCan you pick me up some nectarines\nAnd a pack of smokes\nI think, I think that's all I need\nTonight I'll strip you bare\nYou say how far, I'll take you there\n\nYou lie beside me in the dead of night\nWe love the hot buzz of the city lights\nTo be both far and near\nTo be both there and here\n\nGive me your tired, give me your poor\nGive me a kiss and a set of keys to your front door\nYour hands work hard for justice\nI want them on me now\nI want them on me now\nI want them on me now" },
  { track: 'Bottle and a Gun', lyrics: "Flocks of winter birds patrol the night\nAnd we’re caught beneath a globe of white\nOld warehouses and the railroad yard\nWooden window frames that drip with shards\n\nFlakes of snow upon the air\nSettle on your lashes and your hair\nAnd you look just like an orphan child\nSomething wounded, something wild\n\nAnd I come home with a pocket full of ones\nAnd I come home not hurting anyone\nBut if I come home with a bottle and a gun\nYou better call someone\n\nFlecks of blood on my guitar\nGalaxies of tiny crimson stars\nAnd my fingers worn and raw\nYou break me like I break the law\n\nAnd I come home with a pocket full of ones\nAnd I come home not hurting anyone\nBut if I come home with a bottle and a gun\nYou better call someone\n\nAnd a faded love is all I ask\nAnd I know you’ll never say it back again\nBut I made you cry that Christmas Eve\nWhen I sang ‘Oh Holy Night’ and your heart believed\n\nFlick the lighter for a dying flame\nFor the day when I won’t speak your name\nNow the snow falls harder on our hands\nAs we unravel to a thousand strands\n\nAnd I come home with a pocket full of ones\nAnd I come home not hurting anyone\nBut if I come home with a bottle and a gun\nYou better call someone\nYou better run, run, run" },
  { track: 'Radiate', lyrics: "You and I\nWe have our stories\nWe survive in all our glory\nHad our hard times\nWe had our fun\nNever answered to anyone\n\nI love my friends\nI love this state\nEven though the hour is late\nIt's just our luck\n It's just our fate\nWe still radiate\n\nAll the rooms\nWhere we lived our lives\nLike bees inside our winter hives\nBut when the springtime comes to pass\nWe’ll be free at last\n\nI love my friends\nI love this state\nEven though the hour is late\nIt's just our luck\nIt's just our fate\nWe still radiate\n\nAt a bus stop in the rain\nYou held onto my pain\nAnd  loved me just the same\n\nThe silent snow\nThe blazing fire\nThe corner bar\nThe holy spire\nBear the weight\nThat’s just we do\nI’ll see you soon\nYou know I love you too\n\nI love my friends\nI love this state\nEven though the hour is late\nIt's just our luck\nIt's just our fate\nWe still radiate" },
  { track: 'Close to Jesus', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Wildflowers', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'I Tried', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Infinite December', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Indiana', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Cold Enough', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." }
];

export const blurbs = [
  { track: 'Razor In His Hand', blurb: "The trauma of growing up queer or transgener in today’s world often pushes young people into the darkest corners. I’ve known kids who were thrown out into the streets when they came out and had to sell their bodies to survive. I’ve known young people who have attempted suicide multiple times, and a few of them that have succeeded. One of the few places I felt free and a part of a community when I was teenager and young adult was the club and rave scene. Unfortunately, these spaces were also the one where I was introduced to the substances that would hijack my brain and cause me thirty years of struggle and suffering. I wrote this song for those kids who are going through what I went through and are struggling to find a little slice of peace and humanity in a cruel and unforgiving world. May we all know hope and love, and may our dreams live on." },
  { track: 'On Me Now', blurb: "Falling in love is one of the most exhilarating and amazing feelings in the world, and I wanted to capture that thrill in musical form. I was inspired by the raw, rhythmic guitar playing of early Ani Difranco and the exuberant vocal hiccups of Micheal Jackson and Cyndi Lauper, two of my earliest vocal influences. Part of this song is autobiographical and some of it is wishful thinking. I wanted to capture that feeling of letting go and learning to trust someone, the rush of feeling like you could take on the world together. This song is one of the poppiest I’ve ever recorded and a whole hell of a lot of fun." },
  { track: 'Bottle and a Gun', blurb: "I’ve gone through some messy breakups in my life, but none as devastating to me as the one that inspired this song. I wanted to explore the darkness, the profound sadness and grief, the extremes of emotion and behavior that can result from a broken heart.I’m so proud of the vocals and production on this one, and I really think Chad and I captured the ache of loss really beautifully. Writing this song helped me process some of my deepest hurt, and I’m so proud of the way it turned out. " },
  { track: 'Radiate', blurb: "When I was younger I never thought I’d be a middle-aged man looking back on the first two thirds of my life and trying to make some sense of it. When I wrote ‘Radiate’ I was reflecting on all the misadventures I’ve had with my friends over the years. All the apartments, rooms, and couches I’ve crashed on. All the people who were there to help me through hard times, some who I’m still close to and some whose friendships just lasted for a season. I’ve been saved by many angels, and I’m forever grateful for all of them. This song is also a love letter to Minnesota and the Twin Cities. If I didn’t live here I might not have gotten all the help I’ve needed over the years. So thank you. All of you." },
  { track: 'Close to Jesus', blurb: "I was lucky—I grew up in a church where I felt loved, valued, and affirmed. I was different from other kids, and that congregation made sure I felt safe and supported, giving my musical talent room to shine. Unfortunately, many queer and trans people have the opposite experience and come away feeling judged, condemned, and traumatized. With this song, I wanted to send a clear and strong message to my queer and trans community—and to those who despise us—that God’s love is bigger than human smallness and cruelty. Christ’s love is available to everyone. God created us and loves us as we are. We deserve a relationship with that love—no matter who we are or what we believe. Period." },
  { track: 'Wildflowers', blurb: "In the late 80s, wildfires ravaged forests in Yellowstone  National Park. The burnt trees and vegetation made the soil extremely rich and the following spring and summer there was an explosion of wildflowers that bloomed where the trees had once stood. That image stayed with me over the years and eventually inspired this song. It’s a metaphor for the strength that comes from struggle and the wisdom that comes from growing older. We’re all a part of the circus of the grieving, and sometimes we have to burn before we blossom." },
  { track: 'I Tried', blurb: "I’ve had relationships that were doomed from the start. I’ve also stayed in relationships long after their expiration date. In 2012-2013 I was listening to Taylor Swift’s ‘Red’ album on repeat as I tried to make sense of a failed love affair. That album, with its blending of country and pop, inspired this song. I wanted to write a universal breakup anthem that you want to crank up when you’re driving and sing along with at the top of your lungs. I hope I don’t always think love is overrated…  " },
  { track: 'Infinite December', blurb: "Sometimes my depression makes my life feel like the longest, snowiest, most stressful December. But I have to bundle up, leave the house, and brace myself against the cold anyways. Living with mental illness and complex trauma isn’t easy, but I have been blessed with many everyday saints and angels in my life that have given me the strength and encouragement to keep going and to keep fighting. This song is for them, and for the faith that has sustained me all these years." },
  { track: 'Indiana', blurb: "I spent eight years of my life living in Fort Wayne, Indiana–a city filled with strip malls, chain restaurants, and winding streets that often changed names for no apparent reason. Three rivers converge there and snake their way through the neighborhoods and many parks I used to play in and explore. Being a queer kid in a conservative state is one of the most formative experiences of my life. I had to learn to defend myself with words and how to grow a thick skin that could withstand the cruelty and rejection I endured. I also met some amazing, kind, and compassionate people there who accepted me as I was and admired the strength it took to become the unique individual that I was. I also broke up with my high school sweetheart in Fort Wayne, and that loss (and the impact that relationship had on me) inspired this song." },
  { track: 'Cold Enough', blurb: "Late fall and early winter 2001 was a formative time in my life. The country was reeling from the attacks of September 11th and Henry, Chad, and I were hard at work recording an album with our band Winter Machine. When I wrote ‘Cold Enough’ I was thinking about the regional small talk and cliches we resort to in Minnesota when the weather changes for the colder. I remember singing this song for Henry and Chad and them trying to convince me to include it on the Winter Machine album. I said no, that it was too fresh and that I couldn’t yet perform it the way I wanted to. Here we are twenty-four years later and finally I am releasing this anthem into the world. I’m in love with the harmonies and the feelings I get when I sing it. I thought it would be the perfect way to close the album." }
]

export const about = "This is the album I’ve always wanted to make, and making it was a lifeline for me. These songs span 25 years of my life and were created out of love, loss, grief, addiction, recovery, and survival. I’ve sung them in dark bars and coffee shops, in churches and at funerals, on street corners and bedrooms lit by Christmas lights and candles, and in more than a few treatment centers. They’ve been like prayers to me. They have stood the test of time and been truly lived in.\n\nRecording and producing this album with my dear friend Chad Duntton was one of the most rewarding experiences of my life. It took two years of on-and-off effort, and I am so proud of how beautifully it turned out. I was honored to have my musical soulmate Henry Bishop in the studio to sing harmonies on three of the tracks as well. I hope these songs will move you, make you want to dance, and get stuck in your head the way they have been in mine all these years. This is my love letter to Gen X, and my tribute to the alternative and pop music of the 80s and 90s that inspired me to want to be a songwriter.\n\nI was influenced by artists like Tori Amos, Tracy Chapman, Peter Gabriel, Ani Difranco, Tom Petty, Depeche Mode, The Indigo Girls, Shawn Colvin, and The Smiths. These artists have created a safety and sanctuary in my life, and I hope this album does the same for you in some way. These songs belong to all of us now.\n\nEnjoy."

