export const lyrics = [
  { track: 'Razor In His Hand', lyrics: "Too long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nHunting season in the North woods \nThe jack lights stand the deer so still \nThe hunters take their aim and they shoot to kill \nThe headlights blind him as he hides his hands inside his sweatshirt sleeves \nHis ass got beat black back at school \nNow there's ass for sale on 14th Street \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nNobody knows the trouble he's seen \nThe femme fatale and the attitude queen \nThe coked-up go-go boys downtown that sleep around \nDon't want to come down \nPlatform shoes walking thin white lines \nShots of booze and neon signs \nA knife in the back and a mouth full of trash \nIt's a night in the life of the nightlife \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand  \n\nThere is hope but it's not your hope \nThere are dreams but they're not your dreams \nThere is love but it's not for you \nGo find some other things to do \n\nHe's inching down the runway of the same old club, the same old spot \nHis muscles feel a little small \nHis stomach feels a little soft \nHe's searching left and right to find somebody with a gentle eye \nA song is forming in his head \nA melody to hide inside \n\nToo long in a dark bar with a stiff drink \nToo long in a parked car with a strange man \nToo long on a cold floor with a straight-edge razor in his hand" },
  { track: 'On Me Now', lyrics: "Give me your tired, give me your poor\nGive me a kiss and a set of keys to your front door\nYour hands work hard for justice\nI want them on me now\n\nTurn on the christmas lights, get out your pen\nShow me the way you get inspired again\nDon't ask if I'm ok 'cus\nI'll just lie anyway\n\nCan you pick me up some nectarines\nAnd a pack of smokes\nI think, I think that's all I need\nTonight I'll strip you bare\nYou say how far, I'll take you there\n\nYou lie beside me in the dead of night\nWe love the hot buzz of the city lights\nTo be both far and near\nTo be both there and here\n\nGive me your tired, give me your poor\nGive me a kiss and a set of keys to your front door\nYour hands work hard for justice\nI want them on me now\nI want them on me now\nI want them on me now" },
  { track: 'Bottle and a Gun', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Radiate', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Close to Jesus', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Wildflowers', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'I Tried', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Infinite December', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Indiana', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." },
  { track: 'Cold Enough', lyrics: "Ut enim ad minim veniam,\nquis nostrud exercitation ullamco laboris nisi ut aliquip\nex ea commodo consequat." }
];

export const blurbs = [
  {track: 'The Circus of the Grieving', blurb: "Circus is an evocative exploration of identity, resilience, and the human experience set against the vibrant backdrop of urban nightlife. Through a blend of haunting melodies and introspective lyrics, the album delves into themes of survival, love, and self-discovery, painting a vivid picture of life on the edge. Each track offers a unique narrative, inviting listeners to journey through the complexities of modern existence with raw emotion and compelling storytelling."},
  { track: 'Razor In His Hand', blurb: "A dark, haunting tale of survival and identity in the shadows of the city nightlife." },
  { track: 'On Me Now', blurb: "An intimate exploration of love, desire, and the search for connection in a bustling urban landscape." },
  { track: 'Bottle and a Gun', blurb: "A gritty narrative of desperation and resilience, set against the backdrop of urban decay." },
  { track: 'Radiate', blurb: "A vibrant anthem of self-discovery and empowerment, shining light on the journey within." },
  { track: 'Close to Jesus', blurb: "A soulful reflection on faith, redemption, and the complexities of belief in modern life." },
  { track: 'Wildflowers', blurb: "A poetic ode to freedom and natural beauty, celebrating the untamed spirit within us all." },
  { track: 'I Tried', blurb: "A heartfelt confession of struggle and perseverance, capturing the essence of human vulnerability." },
  { track: 'Infinite December', blurb: "A melancholic yet hopeful meditation on time, memory, and the cycles of life." },
  { track: 'Indiana', blurb: "A nostalgic journey through personal history and the landscapes that shape us." },
  { track: 'Cold Enough', blurb: "A chilling exploration of emotional isolation and the quest for warmth in a cold world." }
]

